fragment CruiseBasicData on Cruise{
  id
  createdAt
  updatedAt
  startDate
  endDate
  ship {
    id
    name
    image
  }
  itinerary {
    name
    location
    length
    image
    gallery 
  }
}
