fragment ShipData on Ship{
  id
  createdAt
  updatedAt
  name
  slug
  excerpt
  description
  image
  shipFeatures
  shipFeaturesText
  foodAndDrinksFeatures
  foodAndDrinksFeaturesText
  divingFeatures
  divingFeaturesText
  gearRental
  gearRentalText
  shipLayout
  shipLayoutText
  shipSpecifications {
    length
    beam
    topSpeed
    cruisingSpeed
    engines
    maxGuests
    bathrooms
    tenders
    waterCapacity
    fuelCapacity
    freshwaterMaker
  }
  shipSpecificationsText
  navSafteyFeatures
  navSafteyFeaturesText
  cabins {
    name
  }
  cabinsText
}
