fragment CruiseData on Cruise{
  id
  createdAt
  updatedAt
  startDate
  endDate
  ship {
    id
    name
    cabins {
      id
      name
      slug
      capacity
      image
    }
  }
  itinerary {
    name
    slug
    location
    length
    dives
    experience
    description
    image
    stopovers {
      title
      description
    }
  }

  accommodations {
    cabin {
      id
      name
      slug
      image
    }
    available
    regularPrice
    salePrice
    saleStartDate
    enabled
  }

}
