fragment CruiseItineraryData on Itinerary{
  name
  slug
  location
  departure {
    location
    time
  }
  return {
    location
    time
  }
  length
  dives
  experience
  description
  image
  stopovers {
    title
    description
  }
}
