fragment CabinData on Cabin{
  id
  createdAt
  updatedAt
  name
  slug
  type
  ensuite
  surface
  balcony
  shower
  bathub
  seaView
  bedding
  pullmanBedding
  airconditioning
  tv
  excerpt
  description
  order
  image
  gallery
  features
  featuresText
  capacity
}
