fragment ShipData on Ship{
  id
  createdAt
  updatedAt
  name
  slug
  excerpt
  description
  image
  gallery
  shipFeatures
  shipFeaturesText
  foodAndDrinksFeatures
  foodAndDrinksFeaturesText
  divingFeatures
  divingFeaturesText
  gearRental
  gearRentalText
  shipLayout
  shipLayoutText
  shipSpecifications {
    yard
    country
    built
    refit
    flag
    classed
    length
    breadth
    maxDraft
    height
    grt
    shipType
    hullMaterial
    superstructure
    hullType
    noOfDecks
    noOfMasts
    crewNo
    noOfEngines
    engineMaker
    power
    cruisingSpeed
    maximumSpeed
    fuelCapacity
    autonomy
    hotWater
    hotWaterType
    airConditioning
    airConditioningType
    waterMaker
    waterMakerCapacity
    bowThruster
    sternThruster
    maxCapacity
    maxCapacityCabins
    dayTrips
    atBerth
    noOfCabins
    operatingLicense
    designation
    availableFor
  }
  shipSpecificationsText
  navSafteyFeatures
  navSafteyFeaturesText
  cabins {
    id
    name
    slug
    capacity
    image
  }
  cabinsText
}
